In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [2]:
df = pd.read_csv('laptop_clean.csv')

In [3]:
df

      Unnamed: 0 Company  TypeName  Inches  Ram  Memory  OpSys  Price_euros
0              0    Acer         3       1    1       3      3       709.00
1              1    Acer         1       1    3       3      1       530.00
2              2    Acer         1       1    1       4      1       659.00
3              3    Acer         1       1    6       3      1       549.00
4              4    Acer         1       1    3       6      1       426.00
...          ...     ...       ...     ...  ...     ...    ...          ...
1258        1298    Vero         1       5    3      10      1       196.00
1259        1299  Xiaomi         2       5    1       4      1       935.00
1260        1300  Xiaomi         1       1    1       4      2      1199.00
1261        1301  Xiaomi         1       1    2       4      2      1399.95
1262        1302  Xiaomi         2       5    1       4      2       999.90

[1263 rows x 8 columns]

In [4]:
df.drop('Unnamed: 0', axis= 1, inplace= True)

In [5]:
df

     Company  TypeName  Inches  Ram  Memory  OpSys  Price_euros
0       Acer         3       1    1       3      3       709.00
1       Acer         1       1    3       3      1       530.00
2       Acer         1       1    1       4      1       659.00
3       Acer         1       1    6       3      1       549.00
4       Acer         1       1    3       6      1       426.00
...      ...       ...     ...  ...     ...    ...          ...
1258    Vero         1       5    3      10      1       196.00
1259  Xiaomi         2       5    1       4      1       935.00
1260  Xiaomi         1       1    1       4      2      1199.00
1261  Xiaomi         1       1    2       4      2      1399.95
1262  Xiaomi         2       5    1       4      2       999.90

[1263 rows x 7 columns]

In [6]:
df.duplicated().sum()

np.int64(37)

In [7]:
df.isnull().sum()

Company        0
TypeName       0
Inches         0
Ram            0
Memory         0
OpSys          0
Price_euros    0
dtype: int64

In [8]:
df

     Company  TypeName  Inches  Ram  Memory  OpSys  Price_euros
0       Acer         3       1    1       3      3       709.00
1       Acer         1       1    3       3      1       530.00
2       Acer         1       1    1       4      1       659.00
3       Acer         1       1    6       3      1       549.00
4       Acer         1       1    3       6      1       426.00
...      ...       ...     ...  ...     ...    ...          ...
1258    Vero         1       5    3      10      1       196.00
1259  Xiaomi         2       5    1       4      1       935.00
1260  Xiaomi         1       1    1       4      2      1199.00
1261  Xiaomi         1       1    2       4      2      1399.95
1262  Xiaomi         2       5    1       4      2       999.90

[1263 rows x 7 columns]

In [9]:
df

     Company  TypeName  Inches  Ram  Memory  OpSys  Price_euros
0       Acer         3       1    1       3      3       709.00
1       Acer         1       1    3       3      1       530.00
2       Acer         1       1    1       4      1       659.00
3       Acer         1       1    6       3      1       549.00
4       Acer         1       1    3       6      1       426.00
...      ...       ...     ...  ...     ...    ...          ...
1258    Vero         1       5    3      10      1       196.00
1259  Xiaomi         2       5    1       4      1       935.00
1260  Xiaomi         1       1    1       4      2      1199.00
1261  Xiaomi         1       1    2       4      2      1399.95
1262  Xiaomi         2       5    1       4      2       999.90

[1263 rows x 7 columns]

In [10]:
df['Company'].unique()

<StringArray>
[     'Acer',     'Apple',      'Asus',     'Chuwi',      'Dell',   'Fujitsu',
        'HP',        'LG',    'Lenovo',       'MSI',  'Mediacom', 'Microsoft',
     'Razer',   'Samsung',   'Toshiba',      'Vero',    'Xiaomi']
Length: 17, dtype: str

In [11]:
company_dic = {'Acer': 0,
    'Apple': 1,
    'Asus': 2,
    'Chuwi': 3,
    'Dell': 4,
    'Fujitsu': 5,
    'HP': 6,
    'LG': 7,
    'Lenovo': 8,
    'MSI': 9,
    'Mediacom': 10,
    'Microsoft': 11,
    'Razer': 12,
    'Samsung': 13,
    'Toshiba': 14,
    'Vero': 15,
    'Xiaomi': 16}
df['Company'] =df['Company'].map(company_dic)

In [12]:
company_dic

{'Acer': 0,
 'Apple': 1,
 'Asus': 2,
 'Chuwi': 3,
 'Dell': 4,
 'Fujitsu': 5,
 'HP': 6,
 'LG': 7,
 'Lenovo': 8,
 'MSI': 9,
 'Mediacom': 10,
 'Microsoft': 11,
 'Razer': 12,
 'Samsung': 13,
 'Toshiba': 14,
 'Vero': 15,
 'Xiaomi': 16}

In [13]:
df

      Company  TypeName  Inches  Ram  Memory  OpSys  Price_euros
0           0         3       1    1       3      3       709.00
1           0         1       1    3       3      1       530.00
2           0         1       1    1       4      1       659.00
3           0         1       1    6       3      1       549.00
4           0         1       1    3       6      1       426.00
...       ...       ...     ...  ...     ...    ...          ...
1258       15         1       5    3      10      1       196.00
1259       16         2       5    1       4      1       935.00
1260       16         1       1    1       4      2      1199.00
1261       16         1       1    2       4      2      1399.95
1262       16         2       5    1       4      2       999.90

[1263 rows x 7 columns]

In [14]:
df.isnull().sum()

Company        0
TypeName       0
Inches         0
Ram            0
Memory         0
OpSys          0
Price_euros    0
dtype: int64

In [15]:
y = df['Price_euros']

In [16]:
y

0        709.00
1        530.00
2        659.00
3        549.00
4        426.00
         ...
1258     196.00
1259     935.00
1260    1199.00
1261    1399.95
1262     999.90
Name: Price_euros, Length: 1263, dtype: float64

In [17]:
x = df[['Company','TypeName','Ram', 'OpSys','Inches']]
y = df['Price_euros']

In [18]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size = 0.3,random_state=10)

In [19]:
model = LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [20]:
model.predict(x_test)

array([ 698.94492124, 1545.37659707,  847.6406952 , 1809.14095961,
        766.58598348,  834.22704572, 1403.78655172,  586.1776633 ,
       1405.76835   ,  914.9538721 , 1459.68183919, 1584.40539433,
       1475.85254284, 1408.99481787, 1552.44929856, 1613.01765931,
        932.96971213,  867.14126786,  723.92147502, 1157.84680576,
       1928.77361152,  770.54958003,  867.14126786,  951.67298574,
        681.25696656, 1279.65808821,  862.10218202, 1914.1397295 ,
       1264.68584557,  681.25696656, 1244.59288749,  702.90851779,
        994.49619924,  832.24524745, 1148.65077764, 1200.67001927,
        617.57950086,  744.93443225, 1152.9527348 , 1578.1216389 ,
        744.93443225, 1554.12254844, 1246.57468577, 1172.05775429,
       1268.64944212, 1457.70004092,  832.24524745, 1009.63762219,
       1279.65808821,  832.24524745, 1926.79181325,  766.58598348,
        834.22704572, 1029.56139996,  702.90851779, 1504.5110164 ,
        929.00611558, 1029.56139996, 1056.36104697, 1408.99481787,
       1852.44406208,  920.90974218, 1108.3802886 , 1387.73881979,
        766.58598348,  748.8980288 , 1408.99481787,  963.73295569,
        702.90851779, 1502.52921813,  766.58598348,  824.31805435,
        824.31805435, 1181.56499977, 1048.97226165, 1008.99902818,
        834.22704572, 1887.17090218, 1152.61437418,  744.93443225,
        893.94091487,  990.5326027 ,  897.90451142, 1371.94781888,
        990.5326027 ,  805.61478075, 1246.57468577,  770.54958003,
        996.64717782,  834.22704572,  826.62773798,  914.9538721 ,
       1373.92961715,  957.61838056, 1104.07833144, 1152.61437418,
       1215.98062252, 1170.07595602, 1172.05775429, 1520.72792864,
       1104.07833144, 1180.9154218 , 1152.61437418,  834.22704572,
        957.61838056,  887.99552005, 1093.23886565, 1172.05775429,
       1403.78655172, 1284.27126273, 1284.27126273,  617.57950086,
       1017.66013505,  961.58197711, 1470.69048528, 1060.32464352,
        830.26344918, 1477.83434112,  777.8899965 , 1172.05775429,
        834.22704572,  918.91746864,  951.67298574,  851.2764064 ,
        834.22704572,  976.08480604,  834.22704572, 1280.30766618,
       1181.56499977, 1104.07833144, 1009.63762219, 1215.98062252,
        918.61723525, 1582.42359606,  926.855137  ,  748.8980288 ,
       1139.31271246, 1485.02413392,  801.6511842 , 1961.85701396,
        702.90851779,  770.54958003, 1914.1397295 ,  893.94091487,
        851.2764064 , 1436.70077386, 1052.22827011, 1371.94781888,
       1405.76835   ,  961.58197711,  770.54958003, 1343.3355539 ,
        530.26868566, 1267.76729857, 1371.94781888, 1169.02463216,
        865.32864989,  834.22704572,  681.25696656, 2106.73099135,
        897.90451142,  996.64717782,  926.855137  , 1502.52921813,
       1371.94781888, 1040.40086574,  532.25048394,  834.22704572,
        830.26344918, 1025.59780341, 1048.97226165, 1865.09614583,
        744.93443225,  820.55450497, 1584.40539433, 1800.78008613,
       1648.08286002,  953.65478401,  926.855137  ,  897.90451142,
       1281.63988648,  961.58197711,  961.58197711,  897.90451142,
       1488.46328448,  706.87211434, 1064.74930078, 1152.61437418,
        957.61838056, 1264.68584557,  681.25696656,  702.90851779,
        897.90451142,  820.55450497, 1284.27126273,  918.91746864,
        986.73818645,  926.855137  ,  974.74160178, 1405.76835   ,
       1200.67001927,  696.96312297, 1140.23271161,  990.5326027 ,
       1246.57468577,  621.54309741, 1458.6063499 , 1172.05775429,
        766.58598348, 1279.65808821, 1093.23886565,  957.61838056,
       1073.01485449,  830.26344918,  834.22704572,  957.61838056,
       1502.52921813,  830.26344918, 1050.41565215,  897.90451142,
       1086.72873736, 1470.69048528,  706.87211434, 1268.64944212,
       2106.73099135, 1246.57468577,  830.26344918, 1281.63988648,
        834.22704572, 1076.97845103, 1473.87074457,  897.90451142,
        854.93976956, 1172.05775429,  926.855137  ,  930.81873355,
       1899.52275254,  887.99552005,  893.94091487, 1711.76032572,
       1281.63988648, 1502.52921813,  702.90851779,  702.90851779,
        930.98791386,  961.58197711,  914.9538721 ,  900.39385061,
       1332.32690781,  965.88393427, 1373.92961715, 1452.74850579,
        828.2816509 ,  975.37532932,  959.60017883,  702.90851779,
       1403.78655172, 1312.14639903,  766.58598348, 1029.56139996,
       1990.46927894, 1502.52921813,  914.9538721 , 1200.67001927,
        918.91746864,  926.855137  , 1180.9154218 ,  702.90851779,
       1539.28967389,  897.90451142,  897.90451142, 1928.77361152,
       1181.56499977,  834.22704572, 1027.57960169,  961.58197711,
        735.82273993,  681.25696656,  863.17767131, 1180.9154218 ,
        996.64717782,  706.87211434,  986.73818645,  957.61838056,
        897.90451142, 2027.51627793, 1617.31961647,  893.94091487,
        766.58598348,  961.58197711,  932.96971213,  961.58197711,
       1038.41906747, 1213.40373262,  961.58197711, 1899.52275254,
        918.91746864,  744.93443225,  914.9538721 , 1192.74282617,
       1405.76835   ,  830.26344918, 1140.65591673,  801.6511842 ,
        768.56778176, 1520.72792864,  744.93443225,  893.94091487,
        830.26344918, 1502.52921813,  744.93443225, 1391.70241634,
       1056.36104697, 1108.3802886 ,  851.2764064 , 1108.3802886 ,
        702.90851779,  820.55450497,  834.22704572, 1089.2752691 ,
        893.94091487,  930.98791386,  867.14126786,  887.99552005,
        851.2764064 ,  798.86161161,  621.54309741, 1200.67001927,
        990.5326027 , 1170.07595602,  957.61838056,  766.58598348,
       1056.36104697, 1284.27126273, 1332.32690781, 1403.78655172,
       1711.76032572, 1009.63762219, 1457.05046295, 1488.46328448,
        914.9538721 , 1609.05406276, 1172.05775429,  961.92033772,
       1681.78602822, 1244.59288749,  930.98791386, 1172.05775429,
       1648.08286002, 1478.55429311, 1405.76835   ,  834.22704572,
       1017.66013505, 1172.05775429,  834.22704572, 1172.05775429,
       1580.10343717, 1044.70282291,  746.91623052,  961.58197711,
       1450.76670751,  897.90451142,  918.91746864,  992.68358128,
       1333.42656253,  957.61838056,  770.54958003, 1119.21975438,
       1646.10106175,  951.67298574, 1389.0710401 ,  996.64717782,
       1244.59288749,  617.57950086,  798.42471633,  893.94091487,
        744.93443225, 1646.10106175,  897.90451142])

In [21]:
print("test score",model.score(x_test,y_test))
print("train score",model.score(x_train,y_train))

test score 0.2832605866436343
train score 0.2046665613403258

In [22]:
df

      Company  TypeName  Inches  Ram  Memory  OpSys  Price_euros
0           0         3       1    1       3      3       709.00
1           0         1       1    3       3      1       530.00
2           0         1       1    1       4      1       659.00
3           0         1       1    6       3      1       549.00
4           0         1       1    3       6      1       426.00
...       ...       ...     ...  ...     ...    ...          ...
1258       15         1       5    3      10      1       196.00
1259       16         2       5    1       4      1       935.00
1260       16         1       1    1       4      2      1199.00
1261       16         1       1    2       4      2      1399.95
1262       16         2       5    1       4      2       999.90

[1263 rows x 7 columns]

In [23]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size = 0.2,random_state=45)

In [24]:
from sklearn.ensemble import RandomForestRegressor

rt = RandomForestRegressor()
rt.fit(X, y)

NameError: name 'X' is not defined

In [ ]:
from sklearn.ensemble import RandomForestRegressor

In [ ]:
rt=RandomForestRegressor()
rt.fit(x_train,y_train)

RandomForestRegressor()

In [ ]:
import os

os.makedirs("model", exist_ok=True)

In [ ]:
import joblib

joblib.dump(rt, "model/rt.lb")

['model/rt.lb']

In [ ]:
print(X.columns)

Index(['Company', 'TypeName', 'Inches', 'Ram', 'Memory', 'OpSys'], dtype='str')

In [ ]:
import os
import joblib

os.makedirs("model", exist_ok=True)

joblib.dump(rt, "model/rt.lb")

print("Saved Successfully")

Saved Successfully

In [ ]:
rt=RandomForestRegressor()
rt.fit(x_train,y_train)

RandomForestRegressor()

In [ ]:
import os

print(os.listdir("model"))

['rt.lb']

In [ ]:
model = joblib.load("model/rt.lb")

In [ ]:
print(rt)

RandomForestRegressor()

In [ ]:
X = df.drop("Price_euros", axis=1)
y = df["Price_euros"]

rt.fit(X, y)

RandomForestRegressor()

In [ ]:
import os
import joblib

os.makedirs("model", exist_ok=True)

joblib.dump(rt, "model/rt.lb")

['model/rt.lb']

In [ ]:
import os
print(os.listdir("model"))

['rt.lb']